"""Silent auto-update for AudioLog.

Flow: a small JSON feed is published with every GitHub release. The updater
polls it, downloads the new signed .app, verifies it three ways (sha256 from
the feed, Developer ID + Team ID, Gatekeeper/notarization), stages it next to
the app data, then hands the bundle swap to a detached shell helper — the
running process cannot replace its own bundle while it is executing inside it.

The helper waits for the old process to exit, swaps the bundle, and asks
launchd to start the app again. Nothing here needs an admin password: the app
lives in /Applications but is owned by the installing user.
"""

import hashlib
import json
import os
import plistlib
import shutil
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path

import version as version_mod
from utils import get_logger

log = get_logger(__name__)

# Releases live in Cloudflare R2, not GitHub Releases: the bucket serves the
# feed and the zip from one public origin, and publishing needs no GitHub
# release to exist. Downloads are pinned to this origin (see _check).
RELEASE_ORIGIN = "https://pub-7c882e4faf9c4890a62908cca4ec2aff.r2.dev"
FEED_URL = f"{RELEASE_ORIGIN}/appcast.json"
TEAM_ID = "BHZHRHKZY4"
BUNDLE_ID = "com.audiolog.app"
LAUNCH_LABEL = "com.audiolog.dictation"

CHECK_DELAY = 90            # first check, seconds after launch
CHECK_INTERVAL = 4 * 3600   # subsequent checks
IDLE_GRACE = 120            # wait this long idle before a silent restart
MAX_DOWNLOAD_BYTES = 800 * 1024 * 1024

_DATA_DIR = Path.home() / "Library" / "Application Support" / "audio-log"
UPDATE_DIR = _DATA_DIR / "updates"
STAGED_APP = UPDATE_DIR / "AudioLog.app"
STAGED_MARKER = UPDATE_DIR / "staged.json"
HELPER_PATH = UPDATE_DIR / "apply-update.sh"
HELPER_LOG = Path.home() / "Library" / "Logs" / "audio-log" / "update.log"

HELPER_SCRIPT = r"""#!/bin/bash
# Generated by AudioLog updater. Swaps the app bundle once the old process
# has exited, then asks launchd (or Launch Services) to start it again.
set -u

STAGED="$1"
TARGET="$2"
LABEL="$3"
MARKER="$4"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
UID_NUM="$(id -u)"

echo "--- $(date '+%Y-%m-%d %H:%M:%S') applying update ---"
echo "staged=$STAGED target=$TARGET"

# Unload the LaunchAgent first. KeepAlive would otherwise relaunch the app
# from the bundle we are about to replace, right in the middle of the swap.
HAD_JOB=0
if launchctl print "gui/$UID_NUM/$LABEL" >/dev/null 2>&1; then
    HAD_JOB=1
    launchctl bootout "gui/$UID_NUM/$LABEL" >/dev/null 2>&1
    echo "launchd job unloaded"
fi

# Give the old instance up to 30s to exit so it is not holding the bundle.
for _ in $(seq 1 60); do
    pgrep -f "$TARGET/Contents/MacOS/" >/dev/null 2>&1 || break
    sleep 0.5
done
pkill -f "$TARGET/Contents/MacOS/" >/dev/null 2>&1
sleep 1

BACKUP="${TARGET}.previous"
rm -rf "$BACKUP"

if [ -d "$TARGET" ] && ! mv "$TARGET" "$BACKUP"; then
    echo "FAILED: cannot move old bundle aside (permissions?)"
    rm -f "$MARKER"
    exit 1
fi

if ditto "$STAGED" "$TARGET"; then
    xattr -dr com.apple.quarantine "$TARGET" 2>/dev/null
    if codesign --verify --strict "$TARGET" 2>/dev/null; then
        echo "OK: swapped, signature verified"
        rm -rf "$BACKUP" "$STAGED"
        rm -f "$MARKER"
    else
        echo "FAILED: swapped bundle does not verify — rolling back"
        rm -rf "$TARGET"
        mv "$BACKUP" "$TARGET"
        rm -rf "$STAGED"
        rm -f "$MARKER"
    fi
else
    echo "FAILED: ditto error — rolling back"
    rm -rf "$TARGET"
    [ -d "$BACKUP" ] && mv "$BACKUP" "$TARGET"
    rm -rf "$STAGED"
    rm -f "$MARKER"
fi

# Restart. Prefer launchd (the app normally runs as a LaunchAgent).
if [ "$HAD_JOB" = "1" ] && [ -f "$PLIST" ]; then
    launchctl bootstrap "gui/$UID_NUM" "$PLIST" && \
        echo "restarted via launchd" || {
            echo "bootstrap failed — falling back to open"
            open -a "$TARGET"
        }
elif launchctl print "gui/$UID_NUM/$LABEL" >/dev/null 2>&1; then
    launchctl kickstart -k "gui/$UID_NUM/$LABEL"
    echo "restarted via launchd (kickstart)"
else
    open -a "$TARGET"
    echo "restarted via open"
fi
"""


# ── bundle / staging helpers ────────────────────────────────────────────────

def installed_app_path() -> Path | None:
    """Path of the running .app bundle, or None when running from source."""
    if not getattr(sys, "frozen", False):
        return None
    try:
        candidate = Path(sys.executable).resolve().parents[2]
    except IndexError:
        return None
    return candidate if candidate.suffix == ".app" else None


def _bundle_plist(app: Path) -> dict:
    with open(app / "Contents" / "Info.plist", "rb") as f:
        return plistlib.load(f)


def _bundle_version(app: Path) -> str:
    try:
        return str(_bundle_plist(app).get("CFBundleShortVersionString") or "0.0.0")
    except Exception:
        return "0.0.0"


def staged_update() -> tuple[str, Path] | None:
    """Return (version, path) of a staged update that is newer than us."""
    if not STAGED_MARKER.exists() or not STAGED_APP.exists():
        return None
    try:
        marker = json.loads(STAGED_MARKER.read_text(encoding="utf-8"))
    except Exception:
        return None
    staged_version = str(marker.get("version") or "")
    if not staged_version:
        return None
    if not version_mod.is_newer(staged_version, version_mod.current()):
        # Already running this version (or newer) — the staging is stale.
        _clear_staging()
        return None
    return staged_version, STAGED_APP


def _clear_staging() -> None:
    for path in (STAGED_MARKER, STAGED_APP):
        try:
            if path.is_dir():
                shutil.rmtree(path, ignore_errors=True)
            else:
                path.unlink(missing_ok=True)
        except Exception:
            log.exception("could not clear staging at %s", path)


def _spawn_helper(staged: Path, target: Path) -> bool:
    """Write the swap helper and launch it detached. True if it started."""
    try:
        UPDATE_DIR.mkdir(parents=True, exist_ok=True)
        HELPER_LOG.parent.mkdir(parents=True, exist_ok=True)
        # encoding is not optional here: inside the py2app bundle there is no
        # locale, so Python defaults to ASCII and the em dash in the helper
        # script raises UnicodeEncodeError — which silently broke every
        # auto-update, since the download and verification had already passed.
        HELPER_PATH.write_text(HELPER_SCRIPT, encoding="utf-8")
        HELPER_PATH.chmod(0o755)
        logfile = open(HELPER_LOG, "a", encoding="utf-8")
        subprocess.Popen(
            ["/bin/bash", str(HELPER_PATH), str(staged), str(target),
             LAUNCH_LABEL, str(STAGED_MARKER)],
            stdout=logfile, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL,
            start_new_session=True,   # survive our own exit / launchd teardown
            cwd="/",
        )
        return True
    except Exception:
        log.exception("could not spawn update helper")
        return False


def apply_staged_at_launch() -> bool:
    """Swap in a staged update before the app initializes.

    Called from run.py. Returns True if a swap was started, in which case the
    caller must exit immediately — the helper restarts the new binary.
    """
    target = installed_app_path()
    if target is None:
        return False
    pending = staged_update()
    if pending is None:
        return False
    staged_version, staged_path = pending
    log.info("applying staged update %s at launch", staged_version)
    return _spawn_helper(staged_path, target)


# ── verification ────────────────────────────────────────────────────────────

def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _run(cmd: list[str]) -> tuple[int, str]:
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    return proc.returncode, (proc.stdout or "") + (proc.stderr or "")


def _verify_bundle(app: Path, expected_version: str) -> str | None:
    """Return None when the bundle is trustworthy, else the reason it isn't."""
    plist = {}
    try:
        plist = _bundle_plist(app)
    except Exception:
        return "Info.plist unreadable"

    if plist.get("CFBundleIdentifier") != BUNDLE_ID:
        return f"wrong bundle id: {plist.get('CFBundleIdentifier')}"
    if str(plist.get("CFBundleShortVersionString")) != expected_version:
        return (f"version mismatch: bundle says "
                f"{plist.get('CFBundleShortVersionString')}, "
                f"feed says {expected_version}")

    code, out = _run(["/usr/bin/codesign", "--verify", "--deep", "--strict",
                      "--verbose=2", str(app)])
    if code != 0:
        return f"codesign --verify failed: {out.strip()[:200]}"

    code, out = _run(["/usr/bin/codesign", "-d", "--verbose=4", str(app)])
    if code != 0:
        return f"codesign -d failed: {out.strip()[:200]}"
    if f"TeamIdentifier={TEAM_ID}" not in out:
        return "signed by an unexpected team"
    if "Developer ID Application" not in out:
        return "not signed with a Developer ID certificate"

    # Gatekeeper: only passes if the build was notarized by Apple.
    code, out = _run(["/usr/sbin/spctl", "--assess", "--type", "execute",
                      "--verbose=4", str(app)])
    if code != 0:
        return f"Gatekeeper rejected the build (not notarized?): {out.strip()[:200]}"

    return None


# ── the updater ─────────────────────────────────────────────────────────────

class Updater:
    """Background update poller.

    is_busy   — callable returning True while recording/transcribing.
    on_staged — called with the new version once it is verified and staged.
    on_apply  — called (from the updater thread) when the app should quit so
                the helper can swap the bundle. Must be thread-safe.
    """

    def __init__(self, config, is_busy=None, on_staged=None, on_apply=None):
        self._config = config
        self._is_busy = is_busy or (lambda: False)
        self._on_staged = on_staged
        self._on_apply = on_apply
        self._thread: threading.Thread | None = None
        self._stop = threading.Event()
        self._lock = threading.Lock()
        self.staged_version: str | None = None
        self.last_error: str | None = None

    # -- public API --

    def start(self) -> None:
        if installed_app_path() is None:
            log.info("updater disabled: not running from an .app bundle")
            return
        if not getattr(self._config, "auto_update", True):
            log.info("updater disabled in settings")
            return
        if env_disabled():
            log.info("updater disabled via AUDIOLOG_NO_UPDATE")
            return
        pending = staged_update()
        if pending is not None:
            self.staged_version = pending[0]
            self._notify_staged()
        self._thread = threading.Thread(target=self._loop, daemon=True,
                                        name="updater")
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()

    def check_now(self) -> tuple[str, str]:
        """Blocking check for the menu item. Returns (status, detail).

        status is one of: "staged", "current", "error".
        """
        if installed_app_path() is None:
            return "error", "Обновления работают только для установленного приложения"
        if self.staged_version:
            return "staged", self.staged_version
        try:
            found = self._check()
        except urllib.error.HTTPError as e:
            log.warning("update feed returned HTTP %s", e.code)
            if e.code == 404:
                # The feed only exists once a release has been published.
                return "error", "Релизов пока не опубликовано"
            return "error", f"GitHub ответил {e.code}"
        except urllib.error.URLError as e:
            log.warning("update feed unreachable: %s", e.reason)
            return "error", "Нет связи с GitHub"
        except Exception as e:
            log.exception("manual update check failed")
            return "error", str(e)
        if found is None:
            return "current", version_mod.current()
        return "staged", found

    def apply_now(self) -> bool:
        """Swap in the staged update and restart. Returns False if nothing."""
        target = installed_app_path()
        pending = staged_update()
        if target is None or pending is None:
            return False
        return _spawn_helper(pending[1], target)

    # -- internals --

    def _loop(self) -> None:
        if self._stop.wait(CHECK_DELAY):
            return
        while not self._stop.is_set():
            try:
                if self.staged_version is None:
                    self._check()
                if self.staged_version is not None:
                    self._maybe_apply_silently()
            except Exception:
                log.exception("update check failed")
            # An update staged but not applied means the app was busy —
            # retry soon rather than waiting out the full poll interval.
            if self._stop.wait(300 if self.staged_version else CHECK_INTERVAL):
                return

    def _fetch_feed(self) -> dict:
        request = urllib.request.Request(
            FEED_URL,
            headers={"User-Agent": f"AudioLog/{version_mod.current()}",
                     "Accept": "application/json"},
        )
        with urllib.request.urlopen(request, timeout=20) as response:
            payload = response.read(1024 * 1024)
        return json.loads(payload.decode("utf-8"))

    def _check(self) -> str | None:
        """Poll the feed; stage a verified update. Returns its version or None."""
        with self._lock:
            feed = self._fetch_feed()
            new_version = str(feed.get("version") or "").strip().lstrip("v")
            url = str(feed.get("url") or "")
            expected_sha = str(feed.get("sha256") or "").lower().strip()
            current = version_mod.current()

            if not new_version or not url or not expected_sha:
                raise ValueError("malformed update feed")
            if not version_mod.is_newer(new_version, current):
                log.info("no update: running %s, feed offers %s",
                         current, new_version)
                return None
            if not url.startswith(f"{RELEASE_ORIGIN}/"):
                raise ValueError(f"refusing download from unexpected host: {url}")

            log.info("update available: %s -> %s", current, new_version)
            self._download_and_stage(url, expected_sha, new_version)
            self.staged_version = new_version
            self.last_error = None
            self._notify_staged()
            return new_version

    def _download_and_stage(self, url: str, expected_sha: str,
                            new_version: str) -> None:
        UPDATE_DIR.mkdir(parents=True, exist_ok=True)
        work = UPDATE_DIR / "work"
        shutil.rmtree(work, ignore_errors=True)
        work.mkdir(parents=True)
        archive = work / "AudioLog.zip"

        request = urllib.request.Request(
            url, headers={"User-Agent": f"AudioLog/{version_mod.current()}"})
        with urllib.request.urlopen(request, timeout=60) as response:
            written = 0
            with open(archive, "wb") as f:
                while True:
                    block = response.read(1024 * 1024)
                    if not block:
                        break
                    written += len(block)
                    if written > MAX_DOWNLOAD_BYTES:
                        raise ValueError("download exceeds size limit")
                    f.write(block)
        log.info("downloaded %.1f MB", written / 1024 / 1024)

        actual_sha = _sha256(archive)
        if actual_sha != expected_sha:
            raise ValueError(
                f"sha256 mismatch: expected {expected_sha}, got {actual_sha}")

        unpacked = work / "unpacked"
        code, out = _run(["/usr/bin/ditto", "-x", "-k", str(archive),
                          str(unpacked)])
        if code != 0:
            raise ValueError(f"unzip failed: {out.strip()[:200]}")

        bundles = list(unpacked.glob("*.app"))
        if len(bundles) != 1:
            raise ValueError(f"expected one .app in archive, found {len(bundles)}")
        new_app = bundles[0]

        reason = _verify_bundle(new_app, new_version)
        if reason is not None:
            raise ValueError(f"refusing update: {reason}")

        _clear_staging()
        shutil.move(str(new_app), str(STAGED_APP))
        STAGED_MARKER.write_text(json.dumps({
            "version": new_version,
            "staged_at": int(time.time()),
            "source": url,
            "sha256": expected_sha,
        }, indent=2), encoding="utf-8")
        shutil.rmtree(work, ignore_errors=True)
        log.info("staged %s at %s", new_version, STAGED_APP)

    def _notify_staged(self) -> None:
        if self._on_staged and self.staged_version:
            try:
                self._on_staged(self.staged_version)
            except Exception:
                log.exception("on_staged callback failed")

    def _maybe_apply_silently(self) -> None:
        """Restart into the new version once the app has been idle a while."""
        if not getattr(self._config, "auto_update_silent", True):
            return
        if self._on_apply is None:
            return
        deadline = time.time() + IDLE_GRACE
        while time.time() < deadline:
            if self._stop.is_set():
                return
            if self._is_busy():
                log.info("busy — postponing update restart")
                return
            time.sleep(5)
        if self._is_busy() or self._stop.is_set():
            return
        log.info("applying update %s (idle)", self.staged_version)
        try:
            self._on_apply()
        except Exception:
            log.exception("on_apply callback failed")


def env_disabled() -> bool:
    """Escape hatch: AUDIOLOG_NO_UPDATE=1 turns the updater off."""
    return os.environ.get("AUDIOLOG_NO_UPDATE") == "1"
